# Generated by Django 5.2 on 2025-06-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_delete_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursos.aula'),
        ),
    ]
