# Generated by Django 5.2 on 2025-06-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_comentario_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
