# Generated by Django 5.2 on 2025-06-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_module_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='video_url',
        ),
        migrations.AddField(
            model_name='aula',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID do vídeo no YouTube'),
        ),
    ]
