# Generated by Django 5.2 on 2025-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_comentario_dislikes_comentario_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pergunta',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
